[package]
name = "sdp-rs"
version = "0.1.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
edition = "2018"

[dependencies]
nom = "6.0.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
ctor = "0.1.16"
color-backtrace = "0.4.2"
