[package]
name = "sdp-rs"
version = "0.1.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
edition = "2018"

[dependencies]
nom = "7"
wee_alloc = { version = "0.4", optional = true }
enum-as-inner = "0.3"

[dependencies.ufmt]
version = "0.1"
features = ["std"]
optional = true

[dependencies.serde]
version = "1"
features = ["derive"]
optional = true

[dependencies.derive-into-owned]
git = "https://github.com/hoodie/derive-into-owned"
branch = "feature/update-syn"

[dev-dependencies]
cfg-if = "1.0.0"
pretty_assertions = "1"
serde_json = "1"

[features]
default = ["udisplay"]
display = []
udisplay = ["ufmt"]
wee = ["wee_alloc"]

[profile.release]
lto = true
opt-level = 's' # try 'z' (size) or 's' (speed)
panic = "abort"

[package.metadata]
wasm-opt = false # in release builds wasm-opt crashes for some reason
