[package]
name = "sdp-rs"
version = "0.1.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
edition = "2018"

[dependencies]
nom = "6.0.1"

[dependencies.ufmt]
version = "0.1.0"
features = ["std"]
optional = true

[dependencies.rogu]
version= "0.2.4"
features = ["ufmt"]
optional = true

[dev-dependencies]
pretty_assertions = "0.6.1"

[features]
default = ["udisplay"]
display = []
udisplay= ["rogu", "ufmt"]

[profile.release]
lto = true
opt-level = 's'
panic = "abort"

