[package]
name = "sdp-rs"
version = "0.1.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
edition = "2018"

[dependencies]
nom = "6.0.1"
wee_alloc = { version = "0.4.5", optional = true }

[dependencies.ufmt]
version = "0.1.0"
features = ["std"]
optional = true

[dev-dependencies]
pretty_assertions = "0.6.1"

[features]
default = ["udisplay"]
display = []
udisplay = ["ufmt"]
wee = ["wee_alloc"]

[profile.release]
lto = true
opt-level = 's'
panic = "abort"
