name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches: '*'

jobs:
  build_test:
    name: build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          #- 1.56.0
    steps:
      - name: check out
        uses: actions/checkout@v2

      - name: setup environment
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features debug 

      - name: test (no default features)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --features debug 

      - name: test (with serde)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features serde,debug

      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
